export default[
    {
        id:1,
        postedOn : '2023-03-28',
        title: 'Accountant',
        company: 'Fragma data Systems',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["Tally",],
        
    },
    {
        id: 2,
        postedOn: '2023-03-24',
        title: "Sales Executive",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["Sales"],
        
      },
      {
        id: 3,
        postedOn: '2023-11-02',
        title: "Cashier",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["Cash Management"],
        
      },
      {
        id: 4,
        postedOn: '2023-11-01',
        title: "Product Developer",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Qrata",
        companyUrl: "https://Jindal Associates.com",
        skills: ["Presentation"]
       
      },
      {
        id:5,
        postedOn : '2023-03-28',
        title: 'Accountant',
        company: 'Saksham enterprises',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["Tally",],
        
    },
    {
        id: 6,
        postedOn: '2023-03-24',
        title: "Sales Executive",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["Sales"],
        
      },
      {
        id: 7,
        postedOn: '2023-11-02',
        title: "Cashier",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["Cash Management"],
        
      },
      {
        id: 8,
        postedOn: '2023-11-01',
        title: "Product Developer",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Saksham enterprises",
        companyUrl: "https://Jindal Associates.com",
        skills: ["Presentation"],
        
      },
      {
        id:9,
        postedOn : '2023-03-28',
        title: 'Accountant',
        company: 'Elite Logistics',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["Tally",],
        
    },
    {
        id: 10,
        postedOn: '2023-03-24',
        title: "Sales Executive",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["Sales"],
        
      },
      {
        id: 11,
        postedOn: '2023-11-02',
        title: "Cashier",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["Cash Management"],
        
      },
      {
        id: 12,
        postedOn: '2023-11-01',
        title: "Product Developer",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Saksham Solutions",
        companyUrl: "https://Jindal Associates.com",
        skills: ["Presentation"],
        
      },
      {
        id:13,
        postedOn : '2023-04-28',
        title: 'Accountant',
        company: 'Zyca Solutions',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["Tally",],
        
    },
    {
        id: 14,
        postedOn: '2023-04-24',
        title: "Sales Executive",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["Sales"],
        
      },
      {
        id: 15,
        postedOn: '2023-11-02',
        title: "Cashier",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["Cash Management"],
        
      },
      {
        id: 16,
        postedOn: '2023-11-01',
        title: "Product Developer",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Health products",
        companyUrl: "https://Jindal Associates.com",
        skills: ["Presentation"],
        
      },
      {
        id:17,
        postedOn : '2023-04-28',
        title: 'Accountant',
        company: 'Life Laboratory',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["Tally",],
        
    },
    {
        id: 18,
        postedOn: '2023-04-24',
        title: "Sales Executive",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["Sales"],
        
      },
      {
        id: 19,
        postedOn: '2023-11-02',
        title: "Cashier",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["Cash Management"],
        
      },
      {
        id: 20,
        postedOn: '2023-11-01',
        title: "Product Developer",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Saskham aesthetics",
        companyUrl: "https://Jindal Associates.com",
        skills: ["Presentation"],
        
      },

      {
        id:21,
        postedOn : '2023-04-28',
        title: 'Accountant',
        company: 'Apple',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["Tally",],
        
    },
    {
        id: 22,
        postedOn: '2023-04-24',
        title: "Sales Executive",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["Sales"],
        
      },
      {
        id: 23,
        postedOn: '2023-11-02',
        title: "Cashier",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["Cash Management"],
        job_link: "https://Jindal Associates.com/careers",
      },
      {
        id: 24,
        postedOn: '2023-11-01',
        title: "Product Developer",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Saskham",
        companyUrl: "https://Jindal Associates.com",
        skills: ["Presentation"],
        job_link: "https://jobs.Saskham.com/",
      },
      {
        id:25,
        postedOn : '2023-04-28',
        title: 'Accountant',
        company: 'Apple',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["Tally",],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id: 26,
        postedOn: '2023-03-24',
        title: "Sales Executive",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["Sales"],
      },
      {
        id: 27,
        postedOn: '2023-11-02',
        title: "Cashier",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["Cash Management"],
        job_link: "https://Jindal Associates.com/careers",
      },
      {
        id: 28,
        postedOn: '2023-11-01',
        title: "Product Developer",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Saskham",
        companyUrl: "https://Jindal Associates.com",
        skills: ["Presentation"],
        job_link: "https://jobs.Saskham.com/",
      },
      {
        id:29,
        postedOn : '2023-03-28',
        title: 'Accountant',
        company: 'Apple',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["Tally",],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id: 30,
        postedOn: '2023-03-24',
        title: "Sales Executive",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["Sales"],
      },
      {
        id: 31,
        postedOn: '2023-11-02',
        title: "Cashier",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["Cash Management"],
        job_link: "https://Jindal Associates.com/careers",
      },
      {
        id: 32,
        postedOn: '2023-11-01',
        title: "Product Developer",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Saskham",
        companyUrl: "https://Jindal Associates.com",
        skills: ["Presentation"],
        job_link: "https://jobs.Saskham.com/",
      },
      {
        id:33,
        postedOn : '2023-03-28',
        title: 'Accountant',
        company: 'Apple',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["Tally",],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id: 34,
        postedOn: '2023-03-24',
        title: "Sales Executive",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["Sales"],
      },
      {
        id: 35,
        postedOn: '2023-11-02',
        title: "Cashier",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["Cash Management"],
        job_link: "https://Jindal Associates.com/careers",
      },
      {
        id: 36,
        postedOn: '2023-11-01',
        title: "Product Developer",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Saskham",
        companyUrl: "https://Jindal Associates.com",
        skills: ["Presentation"],
        job_link: "https://jobs.Saskham.com/",
      },
      {
        id:37,
        postedOn : '2023-10-28',
        title: 'Field Assistant',
        company: 'Apple',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["On-field"],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id: 38,
        postedOn: '2023-10-24',
        title: "Field Assistant",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["On-field"],
      },
      {
        id: 39,
        postedOn: '2023-11-02',
        title: "Field Assistant",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["On-field"],
        job_link: "https://Jindal Associates.com/careers",
      },
      {
        id: 40,
        postedOn: '2023-11-01',
        title: "Field Assistant",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Saskham",
        companyUrl: "https://Jindal Associates.com",
        skills: ["On-field"],
        job_link: "https://jobs.Saskham.com/",
      }, {
        id:41,
        postedOn : '2023-10-28',
        title: 'Field Assistant',
        company: 'Apple',
        type: 'Full Time',
        experience: 'Mid Level',
        location: 'Remote',
        skills: ["On-field"],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id: 42,
        postedOn: '2023-10-24',
        title: "Field Assistant",
        type: "Full time",
        location: "In-office",
        experience: "Fresher",
        company: "TechNo water solutions",
        skills: ["On-field"],
      },
      {
        id: 43,
        postedOn: '2023-11-02',
        title: "Field Assistant",
        type: "Part time",
        location: "Remote",
        experience: "Senior Level",
        company: "Jindal Associates",
        skills: ["On-field"],
        
      },
      {
        id: 44,
        postedOn: '2023-11-01',
        title: "Field Assistant",
        type: "Contract",
        location: "Hybrid",
        experience: "Junior Level",
        company: "Saskham",
        companyUrl: "https://Jindal Associates.com",
        skills: ["On-field"],
        
      },
]